import { HrmListScopeContext } from '../common/hrm-list-scope';
import { HrmDbService } from '../db/hrm-db.service';
import { AttendanceEventFanoutService } from '../notifications/attendance-event-fanout.service';
import { CreateAttendanceUpdateRequestDto } from './dto/create-attendance-update-request.dto';
import { DecideAttendanceUpdateRequestDto } from './dto/decide-attendance-update-request.dto';
import { CreateAttendanceRecordDto } from './dto/create-attendance-record.dto';
import { GetAttendanceRecordQueryDto } from './dto/get-attendance-record.query.dto';
import { ListAttendanceRecordsQueryDto } from './dto/list-attendance-records.query.dto';
import { ListAttendanceUpdateRequestsQueryDto } from './dto/list-attendance-update-requests.query.dto';
import { UpdateAttendanceUpdateRequestDto } from './dto/update-attendance-update-request.dto';
import { UpdateAttendanceStatusDto } from './dto/update-attendance-status.dto';
export declare class AttendanceService {
    private readonly db;
    private readonly attendanceFanout;
    constructor(db: HrmDbService, attendanceFanout: AttendanceEventFanoutService);
    private resolvePage;
    private resolvePageSize;
    private assertCheckInOutOrder;
    private assertValidAttendanceDate;
    private normalizeAttendanceDateForApi;
    private guardAttendanceMutate;
    private loadAttendanceRecordCompany;
    private loadUpdateRequestCompany;
    private ensureSchema;
    private ensureDefaultWorkSite;
    private haversineMeters;
    private assertWithinWorkSite;
    private mapRecord;
    private toAttendanceUpdateRequestRealtimePayload;
    private mapUpdateRequest;
    createRecord(payload: CreateAttendanceRecordDto, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>;
    listRecords(query: ListAttendanceRecordsQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        total: number;
        page: number;
        page_size: number;
        data: {
            id: string;
            company_id: string;
            employee_id: string;
            attendance_date: string | null;
            check_in_at: string | null;
            check_out_at: string | null;
            status: "pending" | "present" | "absent" | "leave";
            note: string | null;
            created_by: string | null;
            created_at: string;
            updated_at: string;
        }[];
    }>;
    getRecordById(recordId: string, query: GetAttendanceRecordQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>;
    updateStatus(recordId: string, payload: UpdateAttendanceStatusDto, requestedCompanyId: string, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>;
    createUpdateRequest(payload: CreateAttendanceUpdateRequestDto, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>;
    listUpdateRequests(query: ListAttendanceUpdateRequestsQueryDto, authorization?: string, tenantId?: string): Promise<{
        total: number;
        data: {
            id: string;
            company_id: string;
            employee_id: string;
            employee_code: string;
            employee_name: string;
            department: string | null;
            position: string | null;
            attendance_date: string | null;
            update_type: string;
            current_check_in: string | null;
            current_check_out: string | null;
            requested_check_in: string | null;
            requested_check_out: string | null;
            reason: string;
            evidence_url: string | null;
            approver_name: string | null;
            status: "pending" | "approved" | "rejected";
            approved_at: string | null;
            rejected_reason: string | null;
            notes: string | null;
            created_at: string;
            updated_at: string;
        }[];
    }>;
    updateUpdateRequest(requestId: string, payload: UpdateAttendanceUpdateRequestDto, requestedCompanyId: string, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>;
    approveUpdateRequest(requestId: string, payload: DecideAttendanceUpdateRequestDto, requestedCompanyId: string, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>;
    rejectUpdateRequest(requestId: string, payload: DecideAttendanceUpdateRequestDto, requestedCompanyId: string, authorization?: string, tenantId?: string): Promise<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>;
    deleteUpdateRequest(requestId: string, requestedCompanyId: string, authorization?: string, tenantId?: string): Promise<{
        id: string;
    }>;
}
