import { AttendanceService } from './attendance.service';
import { AttendanceCatalogService } from './attendance-catalog.service';
import { CreateAttendanceSheetDto } from './dto/create-attendance-sheet.dto';
import { UpdateAttendanceSheetDto } from './dto/update-attendance-sheet.dto';
import { CreateLeaveRequestDto } from './dto/create-leave-request.dto';
import { DecideLeaveRequestDto } from './dto/decide-leave-request.dto';
import { ListLeaveRequestsQueryDto } from './dto/list-leave-requests.query.dto';
import { AttendanceRequestsService } from './attendance-requests.service';
import { LeaveRequestsService } from './leave-requests.service';
import { LeaveBalanceService } from './leave-balance.service';
import { AttendanceOverviewService } from './attendance-overview.service';
import { GetLeaveBalanceQueryDto } from './dto/get-leave-balance.query.dto';
import { AttendanceOverviewQueryDto } from './dto/attendance-overview.query.dto';
import { CreateBusinessTripRequestDto } from './dto/create-business-trip-request.dto';
import { CreateLateEarlyRequestDto } from './dto/create-late-early-request.dto';
import { CreateOvertimeRequestDto } from './dto/create-overtime-request.dto';
import { CreateShiftChangeRequestDto } from './dto/create-shift-change-request.dto';
import { ListAttendanceRequestsQueryDto } from './dto/list-attendance-requests.query.dto';
import { CreateAttendanceUpdateRequestDto } from './dto/create-attendance-update-request.dto';
import { DecideAttendanceUpdateRequestDto } from './dto/decide-attendance-update-request.dto';
import { CreateAttendanceRecordDto } from './dto/create-attendance-record.dto';
import { GetAttendanceRecordQueryDto } from './dto/get-attendance-record.query.dto';
import { ListAttendanceRecordsQueryDto } from './dto/list-attendance-records.query.dto';
import { ListAttendanceUpdateRequestsQueryDto } from './dto/list-attendance-update-requests.query.dto';
import { UpdateAttendanceUpdateRequestDto } from './dto/update-attendance-update-request.dto';
import { UpdateAttendanceStatusDto } from './dto/update-attendance-status.dto';
export declare class AttendanceController {
    private readonly attendanceService;
    private readonly attendanceCatalog;
    private readonly leaveRequestsService;
    private readonly leaveBalanceService;
    private readonly attendanceRequestsService;
    private readonly attendanceOverviewService;
    constructor(attendanceService: AttendanceService, attendanceCatalog: AttendanceCatalogService, leaveRequestsService: LeaveRequestsService, leaveBalanceService: LeaveBalanceService, attendanceRequestsService: AttendanceRequestsService, attendanceOverviewService: AttendanceOverviewService);
    private assertBusinessAccess;
    createRecord(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, body: CreateAttendanceRecordDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    listRecords(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceRecordsQueryDto, headers?: Record<string, unknown>): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        page: number;
        page_size: number;
        data: {
            id: string;
            company_id: string;
            employee_id: string;
            attendance_date: string | null;
            check_in_at: string | null;
            check_out_at: string | null;
            status: "pending" | "present" | "absent" | "leave";
            note: string | null;
            created_by: string | null;
            created_at: string;
            updated_at: string;
        }[];
    }>>;
    getRecord(recordId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: GetAttendanceRecordQueryDto, headers?: Record<string, unknown>): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    updateStatus(recordId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: UpdateAttendanceStatusDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        attendance_date: string | null;
        check_in_at: string | null;
        check_out_at: string | null;
        status: "pending" | "present" | "absent" | "leave";
        note: string | null;
        created_by: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    createUpdateRequest(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, body: CreateAttendanceUpdateRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    listUpdateRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceUpdateRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: {
            id: string;
            company_id: string;
            employee_id: string;
            employee_code: string;
            employee_name: string;
            department: string | null;
            position: string | null;
            attendance_date: string | null;
            update_type: string;
            current_check_in: string | null;
            current_check_out: string | null;
            requested_check_in: string | null;
            requested_check_out: string | null;
            reason: string;
            evidence_url: string | null;
            approver_name: string | null;
            status: "pending" | "approved" | "rejected";
            approved_at: string | null;
            rejected_reason: string | null;
            notes: string | null;
            created_at: string;
            updated_at: string;
        }[];
    }>>;
    updateUpdateRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: UpdateAttendanceUpdateRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    approveUpdateRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideAttendanceUpdateRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    rejectUpdateRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideAttendanceUpdateRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string;
        employee_name: string;
        department: string | null;
        position: string | null;
        attendance_date: string | null;
        update_type: string;
        current_check_in: string | null;
        current_check_out: string | null;
        requested_check_in: string | null;
        requested_check_out: string | null;
        reason: string;
        evidence_url: string | null;
        approver_name: string | null;
        status: "pending" | "approved" | "rejected";
        approved_at: string | null;
        rejected_reason: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
    }>>;
    deleteUpdateRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
    }>>;
    createLeaveRequest(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, body: CreateLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string | null;
        employee_name: string | null;
        leave_type: string;
        start_date: string;
        end_date: string;
        reason: string | null;
        status: string;
        requested_at: string;
        reviewed_at: string | null;
        reviewed_by: string | null;
        department: string | null;
        position: string | null;
        total_days: string;
        handover_to: string | null;
        handover_tasks: string | null;
        approver_employee_id: string | null;
        rejected_reason: string | null;
        attachment_url: string | null;
    }>>;
    getAttendanceOverview(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: AttendanceOverviewQueryDto): Promise<import("../common/api-response").ApiSuccess<import("./attendance-overview.service").AttendanceOverviewPayload>>;
    getLeaveBalance(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: GetLeaveBalanceQueryDto, headers?: Record<string, unknown>): Promise<import("../common/api-response").ApiSuccess<import("./leave-balance.service").LeaveBalancePayload>>;
    listLeaveRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListLeaveRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: {
            id: string;
            company_id: string;
            employee_id: string;
            employee_code: string | null;
            employee_name: string | null;
            leave_type: string;
            start_date: string;
            end_date: string;
            reason: string | null;
            status: string;
            requested_at: string;
            reviewed_at: string | null;
            reviewed_by: string | null;
            department: string | null;
            position: string | null;
            total_days: string;
            handover_to: string | null;
            handover_tasks: string | null;
            approver_employee_id: string | null;
            rejected_reason: string | null;
            attachment_url: string | null;
        }[];
    }>>;
    approveLeaveRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string | null;
        employee_name: string | null;
        leave_type: string;
        start_date: string;
        end_date: string;
        reason: string | null;
        status: string;
        requested_at: string;
        reviewed_at: string | null;
        reviewed_by: string | null;
        department: string | null;
        position: string | null;
        total_days: string;
        handover_to: string | null;
        handover_tasks: string | null;
        approver_employee_id: string | null;
        rejected_reason: string | null;
        attachment_url: string | null;
    }>>;
    rejectLeaveRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        company_id: string;
        employee_id: string;
        employee_code: string | null;
        employee_name: string | null;
        leave_type: string;
        start_date: string;
        end_date: string;
        reason: string | null;
        status: string;
        requested_at: string;
        reviewed_at: string | null;
        reviewed_by: string | null;
        department: string | null;
        position: string | null;
        total_days: string;
        handover_to: string | null;
        handover_tasks: string | null;
        approver_employee_id: string | null;
        rejected_reason: string | null;
        attachment_url: string | null;
    }>>;
    listOvertimeRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createOvertimeRequest(authorization: string | undefined, internalApiKey: string | undefined, body: CreateOvertimeRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    approveOvertimeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    rejectOvertimeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    deleteOvertimeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        deleted: boolean;
    }>>;
    listBusinessTripRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createBusinessTripRequest(authorization: string | undefined, internalApiKey: string | undefined, body: CreateBusinessTripRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    approveBusinessTripRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    rejectBusinessTripRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    deleteBusinessTripRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        deleted: boolean;
    }>>;
    listLateEarlyRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createLateEarlyRequest(authorization: string | undefined, internalApiKey: string | undefined, body: CreateLateEarlyRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    approveLateEarlyRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    rejectLateEarlyRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    deleteLateEarlyRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        deleted: boolean;
    }>>;
    listShiftChangeRequests(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, headerCompanyId: string | undefined, query: ListAttendanceRequestsQueryDto): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createShiftChangeRequest(authorization: string | undefined, internalApiKey: string | undefined, body: CreateShiftChangeRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    approveShiftChangeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    rejectShiftChangeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined, body: DecideLeaveRequestDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    listWorkShifts(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createWorkShift(authorization: string | undefined, internalApiKey: string | undefined, body: Record<string, unknown>): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    updateWorkShift(shiftId: string, authorization: string | undefined, internalApiKey: string | undefined, companyId: string, body: Record<string, unknown>): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    deleteWorkShift(shiftId: string, authorization: string | undefined, internalApiKey: string | undefined, companyId: string): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
    }>>;
    listAttendanceSheets(authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string): Promise<import("../common/api-response").ApiSuccess<{
        total: number;
        data: import("pg").QueryResultRow[];
    }>>;
    createAttendanceSheet(authorization: string | undefined, internalApiKey: string | undefined, body: CreateAttendanceSheetDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    updateAttendanceSheet(sheetId: string, authorization: string | undefined, internalApiKey: string | undefined, companyId: string, body: UpdateAttendanceSheetDto): Promise<import("../common/api-response").ApiSuccess<import("pg").QueryResultRow>>;
    deleteAttendanceSheet(sheetId: string, authorization: string | undefined, internalApiKey: string | undefined, companyId: string): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
    }>>;
    deleteShiftChangeRequest(requestId: string, authorization: string | undefined, internalApiKey: string | undefined, tenantId: string | undefined, companyId: string | undefined): Promise<import("../common/api-response").ApiSuccess<{
        id: string;
        deleted: boolean;
    }>>;
}
