/**
 * API path hints for SRS UC specs (HRM implemented + XBOS patterns).
 */
export const HRM_API_BY_CODE = {
  'UC-HRM-01': { method: 'GET', path: '/api/hrm', op: 'health' },
  'UC-HRM-02': { method: 'POST', path: '/api/hrm/admin/platform-admin', op: 'create' },
  'UC-HRM-03': { method: 'POST', path: '/api/hrm/admin/company-admin', op: 'create' },
  'UC-HRM-04': { method: 'POST', path: '/api/hrm/admin/invite-employee', op: 'create' },
  'UC-HRM-05': { method: 'POST', path: '/api/hrm/admin/reset-user-password', op: 'update' },
  'UC-HRM-06': { method: 'POST', path: '/api/hrm/catalog-sync/pull/:catalogKey', op: 'sync' },
  'UC-HRM-07': { method: 'GET', path: '/api/hrm/catalog-sync/:catalogKey', op: 'read' },
  'UC-HRM-08': { method: 'GET', path: '/api/hrm/catalog-sync', op: 'read' },
  'UC-HRM-12': { method: 'GET', path: '/api/hrm/notifications/inbox', op: 'read' },
  'HRM-SC-02': { method: 'POST', path: '/api/hrm/settings-catalogs/sync-from-xbos', op: 'sync' },
  'HRM-SC-03': { method: 'POST', path: '/api/hrm/settings-catalogs/:catalogKey/extension-items', op: 'create' },
  'UC-HRM-MOB-01': { method: 'POST', path: '/api/hrm/auth/mobile/login', op: 'auth' },
  'UC-HRM-MOB-02': { method: 'POST', path: '/api/hrm/auth/mobile/select-membership', op: 'auth' },
};

const PREFIX_API = [
  [/^HRM-AT-01$/, 'POST', '/api/hrm/attendance/records', 'create'],
  [/^HRM-AT-02$/, 'GET', '/api/hrm/attendance/records', 'read'],
  [/^HRM-AT-03$/, 'PATCH', '/api/hrm/attendance/records/:recordId/status', 'update'],
  [/^HRM-AT-04$/, 'POST', '/api/hrm/attendance/update-requests', 'create'],
  [/^HRM-AT-05$/, 'GET', '/api/hrm/attendance/update-requests', 'read'],
  [/^HRM-AT-06$/, 'PATCH', '/api/hrm/attendance/update-requests/:requestId', 'update'],
  [/^HRM-AT-07$/, 'POST', '/api/hrm/attendance/update-requests/:requestId/approve', 'approve'],
  [/^HRM-AT-08$/, 'POST', '/api/hrm/attendance/update-requests/:requestId/reject', 'reject'],
  [/^HRM-AT-09$/, 'DELETE', '/api/hrm/attendance/update-requests/:requestId', 'delete'],
  [/^HRM-AT-10$/, 'POST', '/api/hrm/attendance/leave-requests', 'create'],
  [/^HRM-AT-11$/, 'GET', '/api/hrm/attendance/leave-requests', 'read'],
  [/^HRM-AT-12$/, 'POST', '/api/hrm/attendance/leave-requests/:requestId/approve', 'approve'],
  [/^HRM-AT-13$/, 'POST', '/api/hrm/attendance/leave-requests/:requestId/reject', 'reject'],
  [/^HRM-SV-01$/, 'POST', '/api/hrm/operations/service-requests', 'create'],
  [/^HRM-SV-02$/, 'GET', '/api/hrm/operations/service-requests', 'read'],
  [/^HRM-SV-03$/, 'PATCH', '/api/hrm/operations/service-requests/:requestId', 'update'],
  [/^HRM-SV-04$/, 'DELETE', '/api/hrm/operations/service-requests/:requestId', 'delete'],
  [/^HRM-SV-05$/, 'POST', '/api/hrm/operations/service-requests/:requestId/approve', 'approve'],
  [/^HRM-SV-06$/, 'POST', '/api/hrm/operations/service-requests/:requestId/reject', 'reject'],
  [/^HRM-NT-01$/, 'PATCH', '/api/hrm/notifications/inbox/:notificationId/read', 'update'],
  [/^HRM-NT-02$/, 'POST', '/api/hrm/notifications/push-tokens', 'create'],
  [/^HRM-EM-01$/, 'POST', '/api/hrm/employees', 'create'],
  [/^HRM-EM-02$/, 'GET', '/api/hrm/employees', 'read'],
  [/^HRM-EM-02A$/, 'GET', '/api/hrm/employees/:employeeId', 'read'],
  [/^HRM-EM-03$/, 'PATCH', '/api/hrm/employees/:employeeId', 'update'],
  [/^HRM-EM-04$/, 'POST', '/api/hrm/employees/:employeeId/archive', 'update'],
  [/^HRM-EM-05$/, 'POST', '/api/hrm/employees/:employeeId/restore', 'update'],
  [/^HRM-PR-01$/, 'POST', '/api/hrm/payroll/periods', 'create'],
  [/^HRM-PR-02$/, 'GET', '/api/hrm/payroll/periods', 'read'],
  [/^HRM-PR-03$/, 'POST', '/api/hrm/payroll/periods/:periodId/process', 'update'],
  [/^HRM-PR-04$/, 'POST', '/api/hrm/payroll/periods/:periodId/close', 'update'],
  [/^HRM-PR-05$/, 'GET', '/api/hrm/payroll/payslips', 'read'],
  [/^HRM-PR-06$/, 'GET', '/api/hrm/payroll/reports/reconciliation', 'read'],
  [/^HRM-RC-01$/, 'POST', '/api/hrm/recruitment/requisitions', 'create'],
  [/^HRM-RC-02$/, 'GET', '/api/hrm/recruitment/requisitions', 'read'],
  [/^HRM-RC-03$/, 'POST', '/api/hrm/recruitment/candidates', 'create'],
  [/^HRM-RC-04$/, 'GET', '/api/hrm/recruitment/candidates', 'read'],
  [/^HRM-RC-05$/, 'POST', '/api/hrm/recruitment/interviews', 'create'],
  [/^HRM-RC-06$/, 'PATCH', '/api/hrm/recruitment/interviews/:interviewId/status', 'update'],
  [/^HRM-CI-01$/, 'POST', '/api/hrm/contracts-insurance/contracts', 'create'],
  [/^HRM-CI-02$/, 'POST', '/api/hrm/contracts-insurance/insurance', 'create'],
  [/^HRM-CI-03$/, 'GET', '/api/hrm/contracts-insurance/contracts', 'read'],
  [/^HRM-CI-04$/, 'GET', '/api/hrm/contracts-insurance/contracts/expiring', 'read'],
  [/^HRM-CI-05$/, 'PATCH', '/api/hrm/contracts-insurance/contracts/:contractId', 'update'],
  [/^HRM-CI-06$/, 'DELETE', '/api/hrm/contracts-insurance/contracts/:contractId', 'delete'],
  [/^HRM-CI-07$/, 'GET', '/api/hrm/contracts-insurance/insurance/expiring', 'read'],
  [/^UC-HRM-22$/, 'GET', '/api/hrm/recruitment/requisitions', 'read'],
  [/^UC-HRM-23$/, 'GET', '/api/hrm/attendance/records', 'read'],
  [/^UC-HRM-24$/, 'GET', '/api/hrm/payroll/periods', 'read'],
  [/^UC-HRM-25$/, 'GET', '/api/hrm/contracts-insurance/contracts', 'read'],
  [/^HRM-MD-01$/, 'POST', '/api/hrm/employee-metadata/change-requests', 'create'],
  [/^HRM-MD-02$/, 'GET', '/api/hrm/employee-metadata/change-requests', 'read'],
  [/^HRM-MD-03$/, 'POST', '/api/hrm/employee-metadata/change-requests/:changeRequestId/approve', 'approve'],
  [/^HRM-MD-04$/, 'POST', '/api/hrm/employee-metadata/change-requests/:changeRequestId/reject', 'reject'],
  [/^HRM-MD-05$/, 'GET', '/api/hrm/employee-metadata/audit-logs', 'read'],
  [/^HRM-SC-01$/, 'GET', '/api/hrm/settings-catalogs', 'read'],
  [/^HRM-SC-04$/, 'POST', '/api/hrm/settings-catalogs/:catalogKey/removal-requests', 'create'],
  [/^HRM-SC-05$/, 'POST', '/api/hrm/settings-catalogs/batches/:batchId/review', 'approve'],
  [/^HRM-SC-06$/, 'POST', '/api/hrm/settings-catalogs/extension-requests/:requestId/reject', 'reject'],
  [/^HRM-SC-07$/, 'POST', '/api/hrm/settings-catalogs/seed/group-employee-import-all', 'bootstrap'],
  [/^HRM-SC-08$/, 'POST', '/api/hrm/settings-catalogs/seed/tenant-position-catalog', 'bootstrap'],
  [/^HRM-SC-09$/, 'POST', '/api/hrm/settings-catalogs/seed/tourism-fleet', 'bootstrap'],
  [/^HRM-IM-01$/, 'POST', '/api/hrm/spreadsheet/import/preview', 'create'],
  [/^HRM-IM-02$/, 'POST', '/api/hrm/spreadsheet/import/commit', 'create'],
  [/^HRM-IM-03$/, 'POST', '/api/hrm/spreadsheet/export', 'create'],
  [/^HRM-IM-04$/, 'GET', '/api/hrm/spreadsheet/templates/:kind', 'read'],
  [/^HRM-OP-01$/, 'POST', '/api/hrm/operations/tasks', 'create'],
  [/^HRM-OP-02$/, 'GET', '/api/hrm/operations/tasks', 'read'],
  [/^HRM-OP-03$/, 'PATCH', '/api/hrm/operations/tasks/:taskId/status', 'update'],
  [/^HRM-OP-04$/, 'GET', '/api/hrm/operations/reports/summary', 'read'],
  [/^HRM-PF-01$/, 'POST', '/api/hrm/performance/cycles', 'create'],
  [/^HRM-PF-02$/, 'GET', '/api/hrm/performance/cycles', 'read'],
  [/^HRM-PF-03$/, 'POST', '/api/hrm/performance/evaluations', 'create'],
  [/^HRM-PF-04$/, 'GET', '/api/hrm/performance/evaluations', 'read'],
  [/^HRM-FL-01$/, 'GET', '/api/hrm/fleet/vehicles', 'read'],
  [/^UC-HRM-MOB-04$/, 'POST', '/api/hrm/attendance/records', 'create'],
  [/^UC-HRM-MOB-06$/, 'POST', '/api/hrm/attendance/leave-requests', 'create'],
  [/^UC-HRM-MOB-08$/, 'POST', '/api/hrm/attendance/leave-requests/:requestId/approve', 'approve'],
  [/^XBOS-DM-HRM-09$/, 'POST', '/api/xbos/catalog-governance/publish', 'update'],
  [/^XBOS-DM-HRM-10$/, 'GET', '/api/hrm/settings-catalogs/sync-from-xbos', 'sync'],
  [/^UC-XBOS-01$/, 'GET', '/api/xbos', 'read'],
  [/^UC-XBOS-02$/, 'POST', '/api/xbos/config-sync/catalog/:catalogKey/publish', 'create'],
  [/^UC-XBOS-03$/, 'GET', '/api/xbos/config-sync/catalog/:catalogKey', 'read'],
  [/^UC-XBOS-04$/, 'GET', '/api/xbos/config-sync/catalogs', 'read'],
  [/^UC-XBOS-05$/, 'POST', '/api/xbos/config-sync/catalog/:catalogKey/publish', 'update'],
  [/^UC-XBOS-06$/, 'GET', '/api/xbos/platform-audit/events', 'read'],
  [/^UC-XBOS-07$/, 'POST', '/api/xbos/alerts/violation-ingest', 'create'],
  [/^UC-XBOS-SYNC-01$/, 'POST', '/api/xbos/config-sync/bootstrap-xevn', 'bootstrap'],
  [/^UC-XBOS-MET-01$/, 'GET', '/api/xbos/metrics', 'read'],
  [/^UC-XBOS-08$/, 'GET', '/api/xbos/business-master/:domain/items', 'read'],
  [/^UC-XBOS-KPI-01$/, 'POST', '/api/xbos/kpi-engine/evaluate', 'create'],
  [/^UC-XBOS-KPI-02$/, 'POST', '/api/xbos/kpi-engine/evaluate-batch', 'create'],
  [/^UC-XBOS-KPI-03$/, 'POST', '/api/xbos/kpi-engine/rollup', 'create'],
  [/^UC-XBOS-KPI-04$/, 'POST', '/api/xbos/kpi-engine/portal-alerts', 'create'],
  [/^UC-XBOS-ORG-01$/, 'GET', '/api/xbos/org-foundation/org-units/tree', 'read'],
  [/^UC-XBOS-ORG-02$/, 'POST', '/api/xbos/org-foundation/org-units', 'create'],
  [/^UC-XBOS-ORG-03$/, 'PUT', '/api/xbos/org-foundation/legal-entities/:entityId', 'update'],
  [/^UC-XBOS-10$/, 'POST', '/api/xbos/org-foundation/segments/:segmentId/promote', 'update'],
  [/^UC-XBOS-11$/, 'GET', '/api/xbos/position-rbac/templates', 'read'],
  [/^UC-XBOS-12$/, 'POST', '/api/xbos/position-rbac/assignments', 'create'],
  [/^UC-XBOS-AUTH-01$/, 'POST', '/api/xbos/auth/login', 'auth'],
  [/^UC-XBOS-AUTH-02$/, 'GET', '/api/xbos/auth/me', 'read'],
  [/^UC-XBOS-TENANT-01$/, 'GET', '/api/xbos/tenant-scope/accessible', 'read'],
  [/^UC-XBOS-TENANT-02$/, 'GET', '/api/xbos/tenant-scope/group-org-overview', 'read'],
  [/^UC-XBOS-TENANT-03$/, 'GET', '/api/xbos/tenant-scope/group-member-units', 'read'],
  [/^UC-XBOS-MD-0[1-7]$/, 'GET', '/api/xbos/business-master/:domain/items', 'read'],
  [/^UC-XBOS-WF-01$/, 'POST', '/api/xbos/workflow-engine/definitions', 'create'],
  [/^UC-XBOS-WF-02$/, 'GET', '/api/xbos/workflow-engine/definitions', 'read'],
  [/^UC-XBOS-WF-03$/, 'POST', '/api/xbos/workflow-engine/instances', 'create'],
  [/^UC-XBOS-WF-04$/, 'POST', '/api/xbos/workflow-engine/tasks/:taskId/complete', 'approve'],
  [/^UC-XBOS-WF-05$/, 'GET', '/api/xbos/workflow-engine/instances/:instanceId/detail', 'read'],
  [/^UC-XBOS-WF-06$/, 'POST', '/api/xbos/workflow-engine/tasks/:taskId/reject', 'reject'],
  [/^UC-XBOS-13$/, 'POST', '/api/xbos/workflow-engine/definitions', 'create'],
  [/^UC-XBOS-14$/, 'POST', '/api/xbos/workflow-engine/instances', 'create'],
  [/^UC-XBOS-15$/, 'GET', '/api/xbos/workflow-engine/reporting-routes', 'read'],
  [/^UC-XBOS-CC-06$/, 'GET', '/api/xbos/workflow-engine/definitions', 'read'],
  [/^UC-XBOS-CAT-05$/, 'POST', '/api/xbos/workflow-engine/tasks/:taskId/complete', 'approve'],
  [/^UC-CC-P0-01$/, 'GET', '/api/xbos/org-foundation/legal-entities/:entityId/shareholders', 'read'],
  [/^UC-CC-P0-02$/, 'GET', '/api/xbos/org-foundation/legal-entities/:entityId/documents', 'read'],
  [/^UC-CC-P0-03$/, 'POST', '/api/xbos/org-foundation/org-units', 'create'],
  [/^UC-CC-P0-04$/, 'GET', '/api/xbos/position-rbac/matrix', 'read'],
  [/^UC-CC-P0-05$/, 'GET', '/api/xbos/config-sync/catalogs', 'read'],
  [/^UC-CC-P0-06$/, 'GET', '/api/xbos/workflow-engine/tasks', 'read'],
  [/^UC-CC-P0-08$/, 'GET', '/api/xbos/command-center/workspace-meta', 'read'],
  [/^UC-ECO-MASTER-02$/, 'POST', '/api/xbos/config-sync/bootstrap-xevn', 'bootstrap'],
  [/^UC-XBOS-AR-01$/, 'GET', '/api/xbos/asset-requests', 'read'],
  [/^UC-XBOS-AR-02$/, 'POST', '/api/xbos/asset-requests', 'create'],
  [/^UC-XBOS-AR-03$/, 'POST', '/api/xbos/asset-requests/:requestId/transition', 'update'],
  [/^UC-XBOS-AST-01$/, 'POST', '/api/xbos/assets', 'create'],
  [/^UC-XBOS-AST-02$/, 'PATCH', '/api/xbos/assets/:assetId', 'update'],
  [/^UC-XBOS-INF-01$/, 'GET', '/api/xbos/infrastructure/settings', 'read'],
  [/^UC-XBOS-INF-02$/, 'PUT', '/api/xbos/infrastructure/settings', 'update'],
  [/^UC-XBOS-INF-03$/, 'GET', '/api/xbos/infrastructure/summary', 'read'],
  [/^XBOS-DM-10$/, 'GET', '/api/xbos/config-sync/catalog/:catalogKey', 'read'],
  [/^XBOS-DM-11$/, 'POST', '/api/xbos/config-sync/catalog/:catalogKey/publish', 'create'],
  [/^XBOS-DM-12$/, 'POST', '/api/xbos/catalog-governance/workflows/start', 'create'],
  [/^XBOS-DM-13$/, 'POST', '/api/xbos/catalog-governance/tasks/:taskId/approve', 'approve'],
  [/^XBOS-DM-14$/, 'GET', '/api/xbos/platform-audit/events', 'read'],
  [/^XBOS-DM-15$/, 'GET', '/api/xbos/catalog-governance/extension-requests', 'read'],
  [/^XBOS-DM-16$/, 'POST', '/api/xbos/catalog-governance/tasks/:taskId/reject', 'reject'],
  [/^XBOS-DM-17$/, 'POST', '/api/xbos/config-sync/catalog/:catalogKey/publish', 'update'],
  [/^XBOS-DM-18$/, 'POST', '/api/xbos/config-sync/catalog/:catalogKey/publish', 'notify'],
];

export function resolveApiHint(code) {
  if (HRM_API_BY_CODE[code]) return HRM_API_BY_CODE[code];
  for (const [re, method, path, op] of PREFIX_API) {
    if (re.test(code)) return { method, path, op };
  }
  if (/^LG-MB-/.test(code)) return { method: 'POST', path: '/api/logistic/mobile/*', op: 'mobile', planned: true };
  if (/^LG-/.test(code)) return { method: 'POST', path: '/api/logistic/*', op: 'action', planned: true };
  if (/^XBOS-DM-/.test(code)) return { method: 'POST', path: '/api/xbos/catalog-governance/*', op: 'config' };
  if (/^UC-XBOS/.test(code) || /^UC-CC/.test(code) || /^UC-RACI/.test(code)) {
    return { method: 'GET', path: '/api/xbos/*', op: 'read' };
  }
  if (/^UC-ECO-SCOPE/.test(code)) return { method: 'GET', path: '/api/*', op: 'scope' };
  if (/^HRM-/.test(code) || /^UC-HRM/.test(code)) {
    return { method: 'GET', path: '/api/hrm/*', op: 'read' };
  }
  return { method: 'POST', path: '/api/*', op: 'action', planned: true };
}

export function errorPrefixForCode(code) {
  if (/^LG-/.test(code)) return 'LG';
  if (/^UC-ECO|^UC-CC/.test(code)) return 'ECO';
  if (/^HRM-|^UC-HRM/.test(code)) return 'HRM';
  return 'XBOS';
}
