# Enterprise PO-Grade BRD for XeVN Ecosystem OS — Full Vietnamese
filepath = "docs/brand-new-documents-20270801/BRD_NEW.md"
L = []

def w(s=""): L.append(s)

# ─────────── HEADER ───────────
w("# BRD-XEVN-NEW v1.0")
w("## Business Requirements — Hệ sinh thái XeVN OS")
w()
w("---")
w()
w("## Lịch sử phiên bản")
w()
w("| Phiên bản | Ngày | Người thực hiện | Nội dung thay đổi |")
w("|---|---|---|---|")
w("| 1.0 | 2026-08-01 | Product Management — XeVN Ecosystem | Bản nháp ban đầu |")
w()
w("---")
w()
w("## Kiểm soát tài liệu (Document Control)")
w()
w("| Mục | Giá trị |")
w("|---|---|")
w("| Tên tài liệu | BRD — Yêu cầu nghiệp vụ — Hệ sinh thái XeVN OS |")
w("| Phiên bản | 1.0 |")
w("| Trạng thái | Bản nháp (Draft) |")
w("| Ngày hiệu lực | 2026-08-01 |")
w("| Người tác giả | Product Management — XeVN Ecosystem |")
w("| Phân loại | Bảo mật nội bộ (Internal Use Only) |")
w("| Khách hàng | Tập đoàn XeVN |")
w("| Nhà cung cấp giải pháp | Unicom Technology Solutions |")
w("| Phê duyệt bởi | Ban điều hành XeVN Group |")
w()
w("---")
w()
w("## Tài liệu tham khảo")
w()
w("| Mã tài liệu | Tên tài liệu |")
w("|---|---|")
w("| SRS-XEVN-NEW v1 | Yêu cầu phần mềm tổng hợp |")
w("| SRS-XEVN-HRM v1 | Yêu cầu phần mềm phân hệ Nhân sự |")
w("| SRS-XEVN-XBOS v1 | Yêu cầu phần mềm phân hệ XBOS |")
w("| TECH_SPEC_NEW.md | Đặc tả kỹ thuật kiến trúc |")
w("| DB_DESIGN_NEW.md | Thiết kế cơ sở dữ liệu |")
w("| API_CONTRACT_NEW.md | Hợp đồng API endpoint |")
w()
w("---")
w()
w("## Mục lục")
w()
w("1. Mục đích và Phạm vi tài liệu")
w("2. Bối cảnh nghiệp vụ và Pain points")
w("3. Phạm vi hệ thống và Ngoài phạm vi")
w("4. Stakeholders và Ma trận Actor")
w("5. Luồng nghiệp vụ chính")
w("   5.1 Luồng Tenant Onboarding")
w("   5.2 Luồng Employee Lifecycle")
w("   5.3 Luồng Leave Approval")
w("   5.4 Luồng Payroll Batch")
w("   5.5 Luồng Recruitment Pipeline")
w("6. Yêu cầu phi chức năng (NFR)")
w("7. Mã lỗi nghiệp vụ")
w("8. Truy xuất nguồn (Traceability)")
w("9. Tiêu chí nghiệm thu (Acceptance Criteria)")
w("10. Phụ lục A: Tài liệu liên quan chi tiết")
w()
w("---")
w()

# ─────────── SECTION 1 ───────────
w("## 1. Mục đích và Phạm vi tài liệu")
w()
w("### 1.1 Mục đích")
w()
w("Tài liệu này mô tả toàn bộ yêu cầu nghiệp vụ cấp chiến lược và tác nghiệp")
w("cho hệ sinh thái **XeVN OS** — nền tảng phần mềm **đa công ty (multi-tenant)**")
w("tập trung vào phân hệ Nhân sự (HRM), Lõi nghiệp vụ (XBOS), Cổng điều hành (Portal/CC)")
w("và Khai thác vận tải (Logistics).")
w()
w("Tài liệu đóng vai trò **căn cứ pháp lý nội bộ** cho việc:")
w("- Quyết định đầu tư và ưu tiên nguồn lực phát triển")
w("- Phân chia rõ ràng \"làm gì / không làm gì\"")
w("- Làm cơ sở kiểm thử nghiệm thu UAT")
w("- Cung cấp audit trail đầy đủ cho Ban điều hành")
w()
w("### 1.2 Phạm vi tài liệu")
w()
w("| Nội dung | Bao gồm | Ghi chú |")
w("|---|---|---|")
w("| Bối cảnh nghiệp vụ | Có | Mô hình vận hành hiện tại |")
w("| Pain points | Có | HR, Fleet, Finance |")
w("| Phạm vi hệ thống theo giai đoạn | Có | Phase 1 & 2 phân chia rõ |")
w("| Máy trạng thái nghiệp vụ | Có | 5 luồng chính |")
w("| Yêu cầu phi chức năng | Có | Performance, Security, DR |")
w("| Ma trận mã lỗi | Có | Business error codes |")
w("| Tiêu chí nghiệm thu UAT | Có | Checklist PO chấm điểm |")
w()
w("### 1.3 Đối tượng độc giả")
w()
w("| Đối tượng | Mục đích sử dụng |")
w("|---|---|")
w("| Ban điều hành XeVN Group | Phê duyệt đầu tư, kiểm soát tiến độ |")
w("| Team Product (PO/BA) | Cơ sở viết SRS, thiết kế DB, API |")
w("| Team Kỹ thuật (BE/FE) | Hiểu nghiệp vụ, xác minh acceptance |")
w("| Đội ngũ QA | Xây dựng test case chức năng & phi chức năng |")
w("| Nhà cung cấp giải pháp | Hiểu rõ yêu cầu, đối chiếu đề xuất |")
w("| Kiểm toán nội bộ | Đọc traceability, đánh giá tính đầy đủ |")
w()
w("---")
w()

# Save intermediate
with open(filepath, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L) + "\n")

print(f"Part 1: {len(L)} lines written")
del L[:]

# ─────────── SECTION 2 ───────────
w()
w("## 2. Bối cảnh nghiệp vụ và Pain points")
w()
w("### 2.1 Mô hình vận hành hiện tại")
w()
w("Tập đoàn XeVN Group vận hành đa ngành, trọng điểm ba mảng:")
w("- **Du lịch & Lữ hành** — Quản lý xe đưa đón khách theo tour, đoàn.")
w("- **Vận tải & Logistics** — Tàu sắp xếp chuyến, xe khách, xe chở hàng, tài xế thuê/điều độ.")
w("- **Dịch vụ & Cho thuê** — Cho thuê phương tiện, trạm/lượt.")
w()
w("Mỗi khu vực kinh doanh được tổ chức thành **pháp nhân (legal entity)** riêng,")
w("có bộ kế toán, bộ nhân sự, bộ số liệu khác biệt.")
w()
w("### 2.2 Pain Points")
w()
w("| STT | Pain Point | Mô tả chi tiết | Mức độ | Nhóm bị ảnh hưởng |")
w("|---|---|---|---|---|")
w("| P-01 | **Data Silos** | HR dùng Excel, Fleet dùng Sheets, Payroll dùng phần mềm riêng. Báo cáo tổng hợp mất 3–5 ngày/tháng | Cao chí mạng | HR, Finance, Fleet |")
w("| P-02 | **HR không chuẩn hóa** | Thang bậc, nghỉ phép, SLA phê duyệt khác nhau giữa các công ty; không có RACI | Cao | HR, Ban lãnh đạo |")
w("| P-03 | **Đăng ký công ty mới chậm** | Setup mất 2–4 tuần: tên, chính sách, danh bạ, nhân sự khởi tạo | Trung bình | Super Admin, IT |")
w("| P-04 | **Chấm công thủ công** | Ký sổ, bấm máy; HR mất vài ngày đối chiếu, nhập liệu | Trung bình | HR, Nhân viên |")
w("| P-05 | **Bảng lương tính tay** | BHXH/BHYT/BHTN/PIT tính Excel, lỗi tay dễ xảy ra | Cao | Finance, HR |")
w("| P-06 | **Tuyển dụng rời rạc** | Đơn gửi qua email, không có pipeline, offer nhầm lẫn | Trung bình | Recruiter, HR |")
w("| P-07 | **Không có audit trail** | Không tra được ai sửa, không truy xuất nguồn cho kiểm toán | Cao | Ban lãnh đạo, IT |")
w("| P-08 | **Rủi ro rò rỉ đa công ty** | Công ty A nhìn thấy dữ liệu B do DB không ngăn cách tenant-by-design | Cao chí mạng | Tất cả |")
w()
w("### 2.3 Bối cảnh kỹ thuật")
w("- Hạ tầng: Cloud VPS, stages dùng chung port 3001 đã bị chiếm — cần tránh xung đột")
w("- Database: phân tán, không single source of truth")
w("- Auth: chưa có SSO, mỗi app tự login riêng")
w("- Monitoring: log tập trung chưa có full APM")
w()
w("---")
w()

with open(filepath, "a", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L) + "\n")

print(f"Part 2 (Section 2): {len(L)} lines")
del L[:]
