import { OnModuleInit } from '@nestjs/common';
import { HrmListScopeContext } from '../common/hrm-list-scope';
import { HrmDbService } from '../db/hrm-db.service';
import { SettingsCatalogsService } from '../settings-catalogs/settings-catalogs.service';
import { CreateEmployeeDto } from './dto/create-employee.dto';
import { EmployeeSummaryQueryDto } from './dto/employee-summary.query.dto';
import { GetEmployeeQueryDto } from './dto/get-employee.query.dto';
import { ListEmployeesQueryDto } from './dto/list-employees.query.dto';
import { UpdateEmployeeDto } from './dto/update-employee.dto';
import type { EmployeeSummaryResult } from './employee-summary.types';
export declare class EmployeesService implements OnModuleInit {
    private readonly db;
    private readonly settingsCatalogs?;
    constructor(db: HrmDbService, settingsCatalogs?: SettingsCatalogsService | undefined);
    private assertJobTitleKeyInCatalog;
    onModuleInit(): Promise<void>;
    private ensureSchema;
    private ensureSeedData;
    private mapEmployee;
    createEmployee(payload: CreateEmployeeDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        id: string;
        company_id: string;
        company_uuid: string | null;
        company_display_name: string | null;
        employee_code: string;
        email: string;
        full_name: string;
        job_title_key: string | null;
        manager_id: string | null;
        status: string;
        hired_at: string | null;
        archived_at: string | null;
        avatar_url: string | null;
        custom_fields: Record<string, string>;
        created_at: string;
        updated_at: string;
    }>;
    private buildEmployeeListFilters;
    private loadAttendanceTodayByEmployeeIds;
    listEmployeeDirectory(query: ListEmployeesQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        total: number;
        page: number;
        page_size: number;
        data: import("./employee-directory").DirectoryListItem[];
    }>;
    getEmployeesSummary(query: EmployeeSummaryQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<EmployeeSummaryResult>;
    listEmployees(query: ListEmployeesQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        total: number;
        page: number;
        page_size: number;
        next_cursor: string | null;
        data: {
            id: string;
            company_id: string;
            company_uuid: string | null;
            company_display_name: string | null;
            employee_code: string;
            email: string;
            full_name: string;
            job_title_key: string | null;
            manager_id: string | null;
            status: string;
            hired_at: string | null;
            archived_at: string | null;
            avatar_url: string | null;
            custom_fields: Record<string, string>;
            created_at: string;
            updated_at: string;
        }[];
    }>;
    private queryEmployeeById;
    getEmployeeDirectoryById(employeeId: string, query: GetEmployeeQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<import("./employee-directory").DirectoryDetailItem>;
    getEmployeeById(employeeId: string, query: GetEmployeeQueryDto, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        id: string;
        company_id: string;
        company_uuid: string | null;
        company_display_name: string | null;
        employee_code: string;
        email: string;
        full_name: string;
        job_title_key: string | null;
        manager_id: string | null;
        status: string;
        hired_at: string | null;
        archived_at: string | null;
        avatar_url: string | null;
        custom_fields: Record<string, string>;
        created_at: string;
        updated_at: string;
    }>;
    updateEmployee(employeeId: string, payload: UpdateEmployeeDto, requestedCompanyId: string, authorization?: string): Promise<{
        id: string;
        company_id: string;
        company_uuid: string | null;
        company_display_name: string | null;
        employee_code: string;
        email: string;
        full_name: string;
        job_title_key: string | null;
        manager_id: string | null;
        status: string;
        hired_at: string | null;
        archived_at: string | null;
        avatar_url: string | null;
        custom_fields: Record<string, string>;
        created_at: string;
        updated_at: string;
    }>;
    archiveEmployee(employeeId: string, requestedCompanyId: string, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        id: string;
        company_id: string;
        company_uuid: string | null;
        company_display_name: string | null;
        employee_code: string;
        email: string;
        full_name: string;
        job_title_key: string | null;
        manager_id: string | null;
        status: string;
        hired_at: string | null;
        archived_at: string | null;
        avatar_url: string | null;
        custom_fields: Record<string, string>;
        created_at: string;
        updated_at: string;
    }>;
    restoreEmployee(employeeId: string, requestedCompanyId: string, authorization?: string, scopeContext?: HrmListScopeContext): Promise<{
        id: string;
        company_id: string;
        company_uuid: string | null;
        company_display_name: string | null;
        employee_code: string;
        email: string;
        full_name: string;
        job_title_key: string | null;
        manager_id: string | null;
        status: string;
        hired_at: string | null;
        archived_at: string | null;
        avatar_url: string | null;
        custom_fields: Record<string, string>;
        created_at: string;
        updated_at: string;
    }>;
}
