/**
 * VP Hà Nội pay-sheet starter — bootstrap catalog rows (open L1, not closed enum).
 * Mirrors scripts/lib/vp-hanoi-payroll-config.mjs for Settings template builder.
 */

export const FORMULA_COL_TONG_THU_NHAP_CODE = 'formula_col_tong_thu_nhap';
export const FORMULA_COL_THUC_LINH_CODE = 'formula_col_thuc_linh';

/** Các khoản khấu trừ trừ khỏi Tổng thu nhập để ra Thực lĩnh (VP Hà Nội). */
export const VP_NET_DEDUCTION_COMPONENT_CODES = [
  'KHAU_TRU_BHXH',
  'KHAU_TRU_CONG_DOAN',
  'KHAU_TRU_VPKL',
  'KHAU_TRU_KE_TOAN',
  'UNG_LUONG_LAN_1',
  'TAM_UNG_KHAC',
  'THUE_TNCN',
  'TRUY_THU',
] as const;

const VP_NET_AGGREGATE_EXPRESSION = [
  'TONG_THU_NHAP',
  ...VP_NET_DEDUCTION_COMPONENT_CODES.map((code) => `- ${code}`),
].join(' ');

export const PAYROLL_AGGREGATE_FORMULA_STARTER_ROWS = [
  {
    code: FORMULA_COL_TONG_THU_NHAP_CODE,
    expression_json: {
      form: 'payroll_aggregate_v1',
      aggregate: 'gross',
      earning_component_codes: [
        'LUONG_THEO_CONG',
        'LUONG_KPI',
        'THUONG_P4',
        'LUONG_OT_150',
        'LUONG_OT_200',
        'LUONG_NGHI_PHEP',
        'LUONG_DOANH_SO',
        'LUONG_ONLINE',
        'LUONG_NGHI_LE',
        'LUONG_KHAC',
        'PC_XANG_XE',
        'TRUY_LINH',
      ],
      ui: {
        label: 'Tổng thu nhập',
        mode: 'sheet_total_column',
        expression:
          'LUONG_THEO_CONG + LUONG_KPI + THUONG_P4 + LUONG_OT_150 + LUONG_OT_200 + LUONG_NGHI_PHEP + LUONG_DOANH_SO + LUONG_ONLINE + LUONG_NGHI_LE + LUONG_KHAC + PC_XANG_XE + TRUY_LINH',
      },
    },
    meta_json: {
      label: 'Cột Tổng thu nhập',
      description_vi: 'Tổng hợp thu nhập trên bảng lương (OV-C)',
    },
  },
  {
    code: FORMULA_COL_THUC_LINH_CODE,
    expression_json: {
      form: 'payroll_aggregate_v1',
      aggregate: 'net',
      ui: {
        label: 'Thực lĩnh',
        mode: 'sheet_total_column',
        expression: VP_NET_AGGREGATE_EXPRESSION,
      },
    },
    meta_json: {
      label: 'Cột Thực lĩnh',
      description_vi: 'Thực lĩnh sau khấu trừ (OV-C)',
    },
  },
] as const;

/** 23 cột VP Hà Nội — bootstrap khi list salary_components (WHERE NOT EXISTS). */
export const VP_PAY_SHEET_STARTER_COMPONENT_ROWS = [
  {
    code: 'LUONG_CO_BAN',
    name: 'Lương cơ bản (P1+P2)',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: true,
    sort_order: 5,
    is_system: true,
    include_in_gross: false,
  },
  {
    code: 'LUONG_THEO_CONG',
    name: 'Lương theo ngày/giờ công',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: true,
    sort_order: 10,
    is_system: true,
  },
  {
    code: 'LUONG_KPI',
    name: 'Lương KPI (P3)',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 20,
    is_system: true,
  },
  {
    code: 'THUONG_P4',
    name: 'Thưởng hiệu quả (P4)',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 30,
    is_system: true,
  },
  {
    code: 'LUONG_OT_150',
    name: 'Lương OT 150%',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 40,
    is_system: true,
  },
  {
    code: 'LUONG_OT_200',
    name: 'Lương OT 200%',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 50,
    is_system: true,
  },
  {
    code: 'LUONG_NGHI_PHEP',
    name: 'Lương ngày phép',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 60,
    is_system: true,
  },
  {
    code: 'LUONG_DOANH_SO',
    name: 'Lương doanh số',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 70,
    is_system: true,
  },
  {
    code: 'LUONG_ONLINE',
    name: 'Lương online',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 80,
    is_system: true,
  },
  {
    code: 'LUONG_NGHI_LE',
    name: 'Lương nghỉ lễ',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 90,
    is_system: true,
  },
  {
    code: 'LUONG_KHAC',
    name: 'Lương khác',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 100,
    is_system: true,
  },
  {
    code: 'PC_XANG_XE',
    name: 'Phụ cấp xăng xe',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 110,
    is_system: true,
  },
  {
    code: 'TRUY_LINH',
    name: 'Truy lĩnh',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: true,
    is_insurance_base: false,
    sort_order: 120,
    is_system: true,
  },
  {
    code: 'KHAU_TRU_BHXH',
    name: 'BHXH/BHYT/BHTN NLĐ',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 200,
    is_system: true,
  },
  {
    code: 'KHAU_TRU_CONG_DOAN',
    name: 'Công đoàn',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 210,
    is_system: true,
  },
  {
    code: 'KHAU_TRU_VPKL',
    name: 'Vi phạm kỷ luật',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 220,
    is_system: true,
  },
  {
    code: 'KHAU_TRU_KE_TOAN',
    name: 'Bảng trừ kế toán',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 230,
    is_system: true,
  },
  {
    code: 'UNG_LUONG_LAN_1',
    name: 'Ứng lương lần 1',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 240,
    is_system: true,
  },
  {
    code: 'TAM_UNG_KHAC',
    name: 'Tạm ứng khác',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 250,
    is_system: true,
  },
  {
    code: 'THUE_TNCN',
    name: 'Thuế TNCN',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 260,
    is_system: true,
  },
  {
    code: 'TRUY_THU',
    name: 'Truy thu',
    component_type: 'thue',
    nature: 'deduction',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 270,
    is_system: true,
  },
  {
    code: 'TONG_THU_NHAP',
    name: 'Tổng thu nhập',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 280,
    is_system: true,
    include_in_gross: false,
  },
  {
    code: 'THUC_LINH',
    name: 'Lương Net',
    component_type: 'luong',
    nature: 'income',
    value_type: 'currency',
    is_taxable: false,
    is_insurance_base: false,
    sort_order: 290,
    is_system: true,
    include_in_gross: false,
  },
] as const;
